version: "3.9"

services:
    pgdb:
        image: postgres:14.5
        container_name: pgdb
        env_file: django_app/.env
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data

    django:
        build:
            context: django_app
            dockerfile: Dockerfile
        container_name: django
        command: /bin/bash -c "exec invoke run"
#        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ./django_app:/usr/src/app
        ports:
            - "8000:8000"
#        expose:
#            - 8000
        depends_on:
            - pgdb
        env_file: django_app/.env

#    react:
#        image: node:18.10.0
#        container_name: react
#        volumes:
#            - ./frontend:/frontend
#        working_dir: /frontend
#        expose:
#            - 3000
#        ports:
#            - "3000:3000"
#        command: bash -c "npm install && npm start"
#
#    nginx:
#        image: nginx:1.23.0
#        container_name: nginx
#        volumes:
#            - ./nginx/dev_nginx.conf:/etc/nginx/conf.d/default.conf
#            - ./django_app/static:/static
#        ports:
#            - "80:80"
##           - "8000:8000"
#        depends_on:
#            - django